version: '3.8'

services:
  web_client:
    build:
      context: ./web_client
      dockerfile: Dockerfile
    ports:
      - "8081:80"  # Podr√°s ver tu web en http://localhost:8081
    depends_on:
      - gateway

  gateway:
    build: 
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - medicos
      - pacientes
      - agendamiento

  broker:
    build: 
      context: ./broker   
      dockerfile: Dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: broker     
    healthcheck:
        test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5

  agendamiento:
    build: 
      context: ./microservicio_agendamiento
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./microservicio_agendamiento:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      broker:
        condition: service_healthy

  notificaciones:
    build: 
      context: ./microservicio_notificaciones
      dockerfile: Dockerfile
    volumes:
      - ./microservicio_notificaciones:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      broker:
        condition: service_healthy

  medicos:
    build: 
      context: ./microservicio_medicos
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./microservicio_medicos:/app
    environment:
      - PYTHONUNBUFFERED=1

  pacientes:
    build: 
      context: ./microservicio_pacientes
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    volumes:
      - ./microservicio_pacientes:/app
    environment:
      - PYTHONUNBUFFERED=1